name: gaming_portal
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.4.1
  get:
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  google_sign_in: 6.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  firebase_ui_oauth_google: ^1.3.3
  firebase_ui_auth: ^1.15.0
  flutter_dice: 
    git: 
      url: https://github.com/ellandar31/FlutterDicePackage
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
