// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqd2irNo8qWOmPRy9RYJ1F4jDnYTawTk0',
    appId: '1:81037857892:web:8b5100d84bc928a5a93b71',
    messagingSenderId: '81037857892',
    projectId: 'gamingportal-1345c',
    authDomain: 'gamingportal-1345c.firebaseapp.com',
    storageBucket: 'gamingportal-1345c.appspot.com',
    measurementId: 'G-0D37YEY2YV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqd2irNo8qWOmPRy9RYJ1F4jDnYTawTk0',
    appId: '1:81037857892:web:506bd25e6c7d8be9a93b71',
    messagingSenderId: '81037857892',
    projectId: 'gamingportal-1345c',
    authDomain: 'gamingportal-1345c.firebaseapp.com',
    storageBucket: 'gamingportal-1345c.appspot.com',
    measurementId: 'G-0SH6G103ZQ',
  );

}